port: 8080
host: 0.0.0.0
run_server: true
file_root: .
postgres: null

image:
  min_file_size: 1024          # 1 KB minimum
  max_file_size: 20971520      # 20 MB maximum

inference:
  type: auto
  vllm:
    port: 8000
    host: 127.0.0.1
    timeout: 7200
    server_args:
      max_model_len: 2048 
      max_num_seqs: 1