port: 8080
host: 0.0.0.0
run_server: true
file_root: .
postgres: null

image:
  min_file_size: 1024          # 1 KB minimum
  max_file_size: 20971520      # 20 MB maximum

inference:
  device: cuda                  # Device for inference: 'cpu' or 'cuda'.
  cache: ./cache