filesystem:
  enabled: True
  permissions:
    - read_file
    - list_directory
    - file_search
  visualize: True
mcp:
  enabled: False
  path: configs/agent/tools/mcp/local.json
ocr:
  enabled: True