defaults:
- vllm: default.yaml
- _self_

provider: vllm
model: Qwen/Qwen3-4B-Instruct-2507-FP8
api_env_var: null

parameters:
  temperature: 0.3
  max_tokens: 4096

vllm_parameters:
  max_model_len: 2048
  max_num_seqs: 1


